global:
  systemDefaultRegistry: ""

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.8.0-rc.1

kubectl:
  image:
    repository: rancher/kubectl
    tag: v1.20.2
